version: '3'

services:
  database:
    build:
      context: ../database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 123

  worker:
    build: 
      context: ../worker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure:3
    depends_on:
      - database
      
  webapp:
    build: 
      context: ../webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure:3
    depends_on:
      - database
