version: '3'

services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
