version: '3'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 123

  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
   # environment:
    #  DB_HOST: docker.mikec123-149382.cloud-edu.emulab.net
    #  DB_PORT: 3306
    # DB_USER: user
    #  DB_PASSWORD: 123
    #  DB_DATABASE: database
   # depends_on:
   #   - database
