apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
<<<<<<< HEAD
  namespace: spotter 
=======
  namespace: spotter
>>>>>>> e75dcefc5f0c962496e0333fd8705895b9f35c76
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
        - name: gethostname
<<<<<<< HEAD
          image: mikec1233/spotter:minideb 
=======
          image: mikec1233/spotter:minideb
>>>>>>> e75dcefc5f0c962496e0333fd8705895b9f35c76
          command: ["/bin/sh", "/scripts/get-hostname.sh"]
          volumeMounts:
            - name: headhostname
              mountPath: /data
            - name: headhostname-script
              mountPath: /scripts
      containers:
        - name: webapp
          image: mikec1233/spotter:webapp.6-4
          ports:
            - name: http-port
              containerPort: 3000
          command: ["/bin/sh", "-c"]
          args:
<<<<<<< HEAD
            - "export HEAD_NODE_HOSTNAME=$(cat /data/head_node_hostname.txt) && exec npm start" 
=======
            - "export HEAD_NODE_HOSTNAME=$(cat /data/head_node_hostname.txt) && exec npm start"
>>>>>>> e75dcefc5f0c962496e0333fd8705895b9f35c76
          volumeMounts:
            - name: headhostname
              mountPath: /data
      volumes:
        - name: headhostname
          emptyDir: {}
        - name: headhostname-script
          configMap:
            name: headhostname-script
<<<<<<< HEAD
=======
            
>>>>>>> e75dcefc5f0c962496e0333fd8705895b9f35c76
            
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mikec1233/spotter:database
        ports:
          - name: http-port
            containerPort: 3306
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: mikec1233/spotter:worker
        ports:
          - name: http-port
            containerPort: 5000
